<a href="https://colab.research.google.com/github/michaeljtang/FingerTracker/blob/main/Ultimate_ds_py_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install jupyterlab_tabnine

     |████████████████████████████████| 178 kB 5.1 MB/s 


# **Numpy**

In [ ]:
import numpy as np

In [ ]:
#random numbers
ran = np.random.rand(2,3)
ran

array([[0.05965754, 0.54177858, 0.44161416],
       [0.53434921, 0.144254  , 0.67110986]])

In [ ]:
#matrix of numbers
full = np.full((2,3),110)
full

array([[110, 110, 110],
       [110, 110, 110]])

In [ ]:
np.count_nonzero(E < T)
#filter matrix by value

In [ ]:
ran[-1]

array([0.53434921, 0.144254  , 0.67110986])

In [ ]:
#concatenate two array vertically
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#concatenate two array horizontally
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
#concatenate two array flattened
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#conventional flatten method 
kaka = np.array([[1, 2, 5],
       [3, 4, 6]])
kaka.flatten()

array([1, 2, 5, 3, 4, 6])

In [ ]:
#normally distributed gaussian 
np.random.normal(size=(2,2))

array([[-1.19753302, -0.20265131],
       [-0.39550145, -2.29847797]])

learn about class
vanishing gradient

In [ ]:
L = np.floor(min(min(X),min(Y))) # lowest quantized bin
H = np.ceil(max(max(X),max(Y))) # highest quantized bin

NameError: ignored

In [ ]:
x=np.random.rand(2,3)
y=np.random.rand(2,3)

In [ ]:
x@y.T

array([[0.74867414, 1.09113947],
       [0.18732985, 0.36570919]])

In [ ]:
np.dot(x,y.T)==x@y.T
#dot product == matrix multiplcation

array([[ True,  True],
       [ True,  True]])

## **Pandas**

load csv list and extract columns

In [ ]:
import pandas as pd

In [ ]:
col_list = ["ThumbZ1", "IndexZ1",'MiddleZ1','RingZ1','PinkyZ1']
df = pd.read_csv("coords.csv", usecols=col_list)
print(df['IndexZ1'])

Load csv as metadata

In [ ]:
#specify csv path
csvpath = '/content/coordsss.csv'
metadata = pd.read_csv(csvpath,on_bad_lines='skip')
print(metadata.head())
thumbx = metadata["IndexX1"]
thumby = np.array(metadata["IndexY1"])


In [ ]:
#insert columns
extracted_features = [1,2,3,4,5]
df = pd.DataFrame(extracted_features)
df.columns = ['feature','label']


zip git repo file to download

In [ ]:
!zip -r /content/file.zip /content/Folder_To_Zip

git clone

In [ ]:
!git clone https://github.com/modestyachts/CIFAR-10.1.git

Intall requirement using txt

In [ ]:
!pip install -r requirements.txt

Concadinate data and label into one dataset

In [ ]:
from torch.utils.data import DataLoader , TensorDataset
dataset = TensorDataset( Tensor(cifar_v6_data), Tensor(cifar_v6_label) )

In [ ]:
x = 2023482348234
print(x % 3)

0


Folder file iteration

In [ ]:
data_dir = "Dataset/"
path_dir = pathlib.Path("Dataset") 
class_names = np.array(sorted([item.name for item in path_dir.glob('*')]))
print(class_names)

['Mild_Demented' 'Moderate_Demented' 'Non_Demented' 'Very_Mild_Demented']